spring:
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true

dubbo:
  registry:
    address: spring-cloud://localhost
  protocol:
    name: dubbo
    port: -1
  cloud:
    subscribed-services: nacos-server